### ISSUE TITLE
2pass is choking itself (is this intended?)

### ISSUE THREAD

**Issue by pencilbook** [ekisu/mpv-webm#78] opened 2020-01-07 13:48 UTC
Settings: https://pastebin.com/D8gjX3pQ

2pass on https://files.catbox.moe/r3h709.webm
2pass off https://files.catbox.moe/jpetf5.webm

**Comment by ekisu** [comment] 2020-01-27 13:03
~~god what is this webm~~

Duplicate of #75, closing.

**Closed by ekisu** 2020-01-27 13:03 UTC
